---
- name: Add unit file for Puma
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
  notify: reload puma

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /etc/db_config
  notify: reload puma

- name: enable puma
  systemd: name=puma enabled=yes
